SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
PLAYER_RADIUS = 20 # ADDED IN 5.
PLAYER_TURN_SPEED = 300 # ADDED IN 6.
PLAYER_SPEED = 200 # ADDED IN 7.
SHOT_RADIUS = 5 # ADDED IN 11. (CH3 - 3)
PLAYER_SHOOT_SPEED = 500 # ADDED IN 11. (CH3 - 3)